---
#########################
#########################
## GitHub Super-Linter ##
#########################
#########################
name: Super-Linter
# https://bit.ly/git-io_workflow-syntax-for-github-actions

#############################
# Start the job on all push #
#############################
on:
  push:

############################
# Ensure safer permissions #
############################
permissions:
  contents: write

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          # Super-Linter requires full repository history for analysis
          fetch-depth: 0
          persist-credentials: false

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: super-linter/super-linter@v8 # zizmor: ignore[unpinned-uses]
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_BIOME_FORMAT: false
          DEFAULT_BRANCH: main
          # Super-Linter requires this variable even if it is unset
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
